# Template beginning {% raw %}
# This workflow is owned by the cookiecutter application, modifications
# should be done on the upstream repo then sync'd with cruft.
name: Update repository with cruft
permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch: # Allow manual triggering
  # schedule disabled for now
  # schedule:
  # - cron: "0 2 * * 1"   # Every Monday at 2am

jobs:
  update-cruft:
    name: Update Cruft
    runs-on:
      labels: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - name: Import Secrets
        id: import-secrets
        uses: hashicorp/vault-action@4c06c5ccf5c0761b6029f56cfb1dcf5565918a3b # v3.4.0
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: approle
          path: approle-gha
          roleId: ${{ secrets.VAULT_APPROLE_ROLE_ID }}
          secretId: ${{ secrets.VAULT_APPROLE_SECRET_ID }}
          namespace: admin
          secrets: >-
            cloud/common/data/cloudflare-zero-trust/service-tokens/pkgs-as-anacondaconnect-com CF_CLIENT_ID | CF_CLIENT_ID ;
            cloud/common/data/cloudflare-zero-trust/service-tokens/pkgs-as-anacondaconnect-com CF_CLIENT_SECRET | CF_CLIENT_SECRET

      - name: Install inject-cloudflare-headers
        run: |
          conda install -q --yes python=3.10 pip conda-forge::conda-lock anaconda-cloud::inject-cloudflare-headers
      - name: Setup Project
        run: make setup

      - name: Configure Git
        shell: bash
        run: |
          git config --global user.email "Anaconda Bot"
          git config --global user.name "devops+anaconda-bot@anaconda.com"
          git config --global url."https://${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}@github.com/".insteadOf "git@github.com:"
          git config --global url."https://${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - name: Check if update is available
        id: check
        shell: bash
        run: |
          CHANGES=0
          if [ -f .cruft.json ]; then
              if ! make cruft-check; then
                  CHANGES=1
              fi
          else
              echo "No .cruft.json file found"
          fi

          echo "has_changes=$CHANGES" >> "$GITHUB_OUTPUT"

      - name: Run cruft update
        if: steps.check.outputs.has_changes == '1'
        shell: bash
        run: |
          make cruft args="--skip-apply-ask"
          git restore --staged .

      - name: Get current date
        if: steps.check.outputs.has_changes == '1'
        id: get-date
        shell: bash
        run: echo "date=$(date -u +"%Y-%m-%d %H:%M:%S UTC")" >> "$GITHUB_OUTPUT"

      - name: Create/Update PR
        if: steps.check.outputs.has_changes == '1'
        id: create-pr
        uses: peter-evans/create-pull-request@84ae59a2cdc2258d6fa0732dd66352dddae2a412 # v7.0.9
        with:
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          add-paths: .
          commit-message: "chore: update from Cruft template"
          branch: "cruft/update"
          delete-branch: true
          title: "New updates detected with Cruft"
          body: |
            This is an autogenerated PR. Review and merge these template updates from Cruft.

            [Cruft](https://cruft.github.io/cruft/) has detected updates from the Cookiecutter repository.

            **Last updated**: ${{ steps.get-date.outputs.date }}

            ## What to do:
            - **To accept these changes**: Review and merge this PR
            - **To reject these changes**: Close this PR without merging

# Template end {% endraw %}
